# Generated by Django 6.0.6 on 2026-07-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IssueCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('ai_summary', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('severity_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('mentions_count', models.IntegerField(default=1)),
                ('sentiment', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('pending_ai', 'Pending AI Review'), ('pending_dept', 'Pending Department'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='pending_ai', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
