# Generated by Django 6.0.6 on 2026-07-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_issuecluster_action_log_issuecluster_center_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuecluster',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='issuecluster',
            name='ward',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
