# Generated by Django 6.0.6 on 2026-07-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_issuecluster_city_issuecluster_ward'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyBriefing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField()),
                ('executive_summary', models.TextField()),
                ('critical_bottleneck', models.TextField()),
                ('successful_resolution', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
