# Generated by Django 4.2.30 on 2026-07-07 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_issuecluster_ward'),
        ('analysis', '0004_weeklybriefing'),
    ]

    operations = [
    ]
