# Generated by Django 6.0.6 on 2026-07-05 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField()),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='complaints/audio/')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='complaints/images/')),
                ('category', models.CharField(choices=[('roads', 'Roads & Infrastructure'), ('water', 'Water Supply'), ('electricity', 'Electricity'), ('sanitation', 'Sanitation & Waste'), ('other', 'Other')], default='other', max_length=50)),
                ('ward', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='analysis.issuecluster')),
            ],
        ),
    ]
